# Generated by Django 3.2.24 on 2024-02-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('yearofpublish', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
